name: go-ci
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - run: go mod download
      - run: go test -v
      - run: go run main.go