name: go-ci
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - run: go mod download
      - run: go test -v
      - run: go run main.go
      
      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: edsonjuniordev/go-ci:latest